//
//  RACSignal+RCLAnimationAdditions.h
//  ReactiveCocoaLayout
//
//  Created by Justin Spahr-Summers on 2013-01-04.
//  Copyright (c) 2013 GitHub. All rights reserved.
//

#import <ReactiveCocoa/ReactiveCocoa.h>

// Defines the curve (timing function) for an animation.
//
// RCLAnimationCurveDefault   - The default or inherited animation curve.
// RCLAnimationCurveEaseInOut - Begins the animation slowly, speeds up in the
//                              middle, and then slows to a stop.
// RCLAnimationCurveEaseIn    - Begins the animation slowly and speeds up to
//                              a stop.
// RCLAnimationCurveEaseOut   - Begins the animation quickly and slows down to
//                              a stop.
// RCLAnimationCurveLinear    - Animates with the same pace over the duration of
//                              the animation.
#ifdef __IPHONE_OS_VERSION_MIN_REQUIRED
    typedef enum : UIViewAnimationOptions {
        RCLAnimationCurveDefault = 0,
        RCLAnimationCurveEaseInOut = UIViewAnimationOptionCurveEaseInOut,
        RCLAnimationCurveEaseIn = UIViewAnimationOptionCurveEaseIn,
        RCLAnimationCurveEaseOut = UIViewAnimationOptionCurveEaseOut,
        RCLAnimationCurveLinear = UIViewAnimationOptionCurveLinear
    } RCLAnimationCurve;
#elif TARGET_OS_MAC
    typedef enum : NSUInteger {
        RCLAnimationCurveDefault,
        RCLAnimationCurveEaseInOut,
        RCLAnimationCurveEaseIn,
        RCLAnimationCurveEaseOut,
        RCLAnimationCurveLinear
    } RCLAnimationCurve;
#endif

// Determines whether the calling code is running from within -animate (or
// a variant thereof).
//
// This can be used to conditionalize behavior based on whether a signal
// somewhere in the chain is supposed to be animated.
//
// This function is thread-safe.
extern BOOL RCLIsInAnimatedSignal(void);

#ifndef __IPHONE_OS_VERSION_MIN_REQUIRED

// Returns the current custom animation, or nil if there is no custom animation.
extern CAAnimation * RCLCurrentAnimation(void);

#endif

@interface RACSignal (RCLAnimationAdditions)

// Wraps every next in an animation block, using the default duration and
// animation curve.
//
// Binding the resulting signal to a view property will result in updates to
// that property (that originate from the signal) being automatically animated.
//
// To delay an animation, use -[RACSignal delay:] or -[RACSignal throttle:] on
// the receiver _before_ applying -animate. Because the aforementioned methods
// delay delivery of `next`s, applying them _after_ -animate will cause values
// to be delivered outside of any animation block.
//
// Returns a signal which animates the sending of its values. Deferring the
// signal's events or having them delivered on another thread is considered
// undefined behavior.
- (RACSignal *)animate;

// Invokes -animateWithDuration:curve: with a curve of RCLAnimationCurveDefault.
- (RACSignal *)animateWithDuration:(NSTimeInterval)duration;

// Behaves like -animate, but uses the given duration and animation curve
// instead of the defaults.
- (RACSignal *)animateWithDuration:(NSTimeInterval)duration curve:(RCLAnimationCurve)curve;

#ifndef __IPHONE_OS_VERSION_MIN_REQUIRED

// Behaves like -animate, but animates with the given animation.
//
// animation - The animation to use to animate changes in this signal. Cannot be
//             nil.
//
// Returns a signal like -animate which animates the sending of its values.
- (RACSignal *)animateWithAnimation:(CAAnimation *)animation;

#endif

// An interpolation block.
//
// progress - 0.0 to 1.0. Represents the progress of the animation, with 0 being
//            the start and 1 being the end.
//
// Returns the value for the progress point. This may be greater than 1 or less
// than 0, where 1 is the end frame and 0 is the starting frame.
typedef CGFloat (^RCLInterpolationBlock)(CGFloat progress);

// An interpolation block which bounces past its end frame before converging
// on it.
extern RCLInterpolationBlock RCLBounceInterpolation(void);

// Behaves like -animateWithDuration:, but interpolates from the previously sent
// value (or `start` on the first value) to the new value, using values
// generated by the `interpolate` block.
//
// duration    - The duration of the animation.
// start       - The value used as the previous value for the first `next` sent.
//               Cannot be nil.
// interpolate - The block used to interpolate. Cannot be nil.
//
// Returns a signal like -animate which animates the sending of its values.
- (RACSignal *)animateWithDuration:(NSTimeInterval)duration start:(id)start interpolate:(RCLInterpolationBlock)interpolate;

// Injects side effects whenever an animation triggered by the receiver
// completes, or whenever the receiver sends a non-animated value.
//
// This is equivalent to -doNext: if applied to a signal that does not animate.
//
// block - A block to execute when animations complete or non-animated values
//         are sent. The block will be passed the non-animated value, or the
//         value that triggered the animation which is now complete. This block
//         must not be nil.
//
// Returns a signal which forwards all the events of the receiver.
- (RACSignal *)doAnimationCompleted:(void (^)(id))block;

// Completes only after the animated signal has completed *and* all running
// animations have completed.
- (RACSignal *)completeAfterAnimations;

@end
